### ISSUE TITLE
InvalidByronCbor on testnet address

### ISSUE THREAD

**Issue by SebastienGllmt** [txpipe/pallas#156]
This transaction fails [e5b25864a3f682fdd3bda195e8e2022835328f45e6a89de3f68a0bcf973ca155](https://testnet.cardanoscan.io/transaction/e5b25864a3f682fdd3bda195e8e2022835328f45e6a89de3f68a0bcf973ca155)

Failure happens on this line: https://github.com/dcSpark/carp/blob/main/indexer/tasks/src/multiera/multiera_outputs.rs#L96

**Comment by scarmuega** [comment]
Seems that the issue described was already fixed in latest code from `main`. Since the `tasks` crate in Carp repo is currently referencing Pallas via git directly without a lock file, it's possible that it has a cached dependency that points to a previous commit.

DISCLAIMER: AFAIK, I was the one introducing the git reference in the Cargo.toml file as a temporal solution while contributing with the Babbage update.

I've just released an official v0.12 of Pallas to crates.io. I suggest using that source as dependency in Carp.
